name: Generate PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Pandoc
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc

    - name: Install LaTeX
      run: |
        sudo apt-get install -y texlive-latex-base texlive-latex-extra texlive-fonts-recommended

    - name: Run make
      run: make pdf

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: workbench-doc.pdf
        path: workbench-doc.pdf
        retention-days: 90

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        tag_name: latest
        files: workbench-doc.pdf
        body: "Workbench design doc"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
